init python:
    def shop_test_add():
        for i in item_clothes_list:
            shop_test.take(i)



label clothes:
    $ item_clothes_list = []


    $ item_hat_1 = Item("POMPON BEANIE", "A ponpon beanie.", "item_hat_1", type="hat", value=50, hair="loose")
    $ item_hat_2 = Item("SANTA HAT", "A festive Santa hat.", "item_hat_2", type="hat", hair="loose", locked_always=True)
    $ item_hat_3 = Item("WITCHES HAT", "A pointed witches hat.", "item_hat_3", type="hat")
    $ item_hat_4 = Item("CAT EARS", "An attachable set of cat ears.", "item_hat_4", type="hat")
    $ item_hat_5 = Item("VISOR HAT", "An open headed cap with a beak to help block the sun but stay cool.", "item_hat_5", type="hat", value=100, fringe=False)
    $ item_hat_6 = Item("WIDE BRIM SUN HAT", "A large hat for wearing in the sun to keep cool and protect from sunburn.", "item_hat_6", type="hat", value=100, hair="loose")
    $ item_hat_7 = Item("BUNNY EARS", "A set of bunny ears.", "item_hat_7", type="hat", value=100, locked_always=True)
    $ item_hat_8 = Item("MAID BONNET", "A frilly maid bonnet.", "item_hat_8", type="hat", value=20, locked_always=True)
    $ item_hat_9 = Item("GHOST HEAD", "A spooky season ghost head.", "item_hat_9", type="hat", hair="bun", fringe=False, value=25, locked_always=True)
    $ item_hat_10 = Item("HUCOW EARS", "Floppy cow ears.", "item_hat_10", type="hat", value=25, locked_always=True)


    $ item_bra_1 = Item("FULL CUP BRA", "A full cup bra giving ample support.", "item_bra_1", type="bra", clevage=True, value=50, exposed_nips="pri")
    $ item_bra_2 = Item("SPORTS BRA", "A supportive sports bra with a mesh front for ventilation.", "item_bra_2", type="bra", clevage=True, value=50)
    $ item_bra_3 = Item("SPORTS BRA", "A simple sports bra.", "item_bra_3", type="bra", clevage=True, value=50)
    $ item_bra_4 = Item("STRAPLESS BRA", "A strapless bra offering modest support.", "item_bra_4", type="bra", clevage=True, value=50)
    $ item_bra_5 = Item("STRAPLESS SHELF BRA", "A bra that only acts as support and does little for modesty.", "item_bra_5", type="bra", clevage=True, braless=True, value=50, exposed_nips=True)
    $ item_bra_6 = Item("OPEN FRONT BRA", "A sexy bra that gives support but also exposes your nipples. Perfect for a night out or in.", "item_bra_6", type="bra", clevage=True, braless=True, value=150, exposed_nips=True)
    $ item_bra_7 = Item("STRING FRONT BRA", "A top masquerading as a bra. Covers breasts and not a lot else.", "item_bra_7", type="bra", clevage=True, value=150, exposed_nips="pri")
    $ item_bra_8 = Item("HOMEMADE WRAP BRA", "A bra made of scrap cloth.", "item_bra_8", type="bra", clevage=True, value=10)
    $ item_bra_9 = Item("FRILLY BRA", "A bra with a frilly trim.", "item_bra_9", type="bra", clevage=True, value=50)
    $ item_bra_10 = Item("TRIANGLE BRA", "A triangle busted bra. Doesn't offer much support but looks nice.", "item_bra_10", type="bra", clevage=True, value=50, exposed_nips="pri")
    $ item_bra_11 = Item("SIMPLE BRA", "A simple bra that doesn't offer any support, but covers where it is needed to.", "item_bra_11", type="bra", clevage=True, value=50, exposed_nips="pri")
    $ item_bra_12 = Item("HALF CUP BRA", "A half cup bra giving good support.", "item_bra_12", type="bra", clevage=True, value=50, exposed_nips="pri")
    $ item_bra_13 = Item("HUCOW BRA", "A bra that doesn't offer much support. But prevents milk leakage and has a cow pattern.", "item_bra_13", type="bra", clevage=True, value=50, locked_always=True)
    $ item_bra_14 = Item("HEART PASTIES", "Hearts taped over the nipples. These also prevent nipple poke through clothing.", "item_bra_14", type="bra", braless=True, perverted=True, bra_nolift=True, value=150)


    $ item_pants_1 = Item("BRIEFS", "A simple pair of cotton briefs.", "item_pants_1", type="pants", value=35, exposed_vag="pri")
    $ item_pants_2 = Item("BRIEFS", "A simple pair of cotton briefs.", "item_pants_2", type="pants", value=35, exposed_vag="pri")
    $ item_pants_3 = Item("HIPSTER BRIEFS", "A pair of hipster briefs.", "item_pants_3", type="pants", value=35, exposed_vag="pri")
    $ item_pants_4 = Item("BOY SHORTS", "A pair of boy shorts.", "item_pants_4", type="pants", value=35, exposed_vag="pri")
    $ item_pants_5 = Item("G-STRING", "A pair of g-string panties.", "item_pants_5", type="pants", thong=True, value=60, exposed_vag="pri", exposed_ass=True)
    $ item_pants_6 = Item("BARGIRL KNICKERS", "Cheap pair of underwear provided by the cock and goose.", "item_pants_6", type="pants", value=25, exposed_vag="pri", exposed_ass=True, locked_always=True)
    $ item_pants_7 = Item("STRIP THONG", "A pair of thong knickers that only covers the strip area.", "item_pants_7", type="pants", thong=True, value=40, exposed_vag="sec", exposed_ass=True)
    $ item_pants_8 = Item("HIGH LEG THONG", "A pair of high legged thong knickers.", "item_pants_8", type="pants", thong=True, value=60, exposed_vag="pri", exposed_ass=True)
    $ item_pants_9 = Item("OPEN CROTCH PANTIES", "A sexy pair of crotchless knickers. Perfect for sexiness or easy access.", "item_pants_9", type="pants", pantsless=True, thong=True, value=150, exposed_vag=True, exposed_ass=True)
    $ item_pants_10 = Item("LOW RIDE PANTS", "A pair of underwear designed to be worn very low on the hips.", "item_pants_10", type="pants", value=80, exposed_vag="pri", exposed_ass=True)
    $ item_pants_11 = Item("C STRING", "A very discreet and uncomfortable set of underwear.", "item_pants_11", type="pants", thong=True, value=80, exposed_ass=True)
    $ item_pants_12 = Item("CROSS STRING", "A small thong with a cross string pattern at the front.", "item_pants_12", type="pants", thong=True, value=80, exposed_ass=True)
    $ item_pants_13 = Item("FRILLY PANTIES", "A pair of frilly panties that goes well with the maid dress.", "item_pants_13", type="pants", value=40, locked_always=True)
    $ item_pants_14 = Item("HOME MADE WRAP KNICKERS", "A pair of knickers using scrap cloth.", "item_pants_14", type="pants", thong=True, value=10)
    $ item_pants_15 = Item("STRAPPY UNDERWEAR", "A pair of knickers with strappy sides.", "item_pants_15", type="pants", thong=True, value=80, exposed_ass=True)
    $ item_pants_16 = Item("HUCOW PANTS", "A pair of knickers with a cow print.", "item_pants_16", type="pants", thong=True, value=80, exposed_ass=True, locked_always=True)

    $ item_bsuit_1 = Item("STRING BODYSUIT", "A bodysuit made mostly of thin strips.", "item_bsuit_1", type="bsuit", thong=True, braless=True, value=80, exposed_ass=True, exposed_nips=True)
    $ item_bsuit_2 = Item("UNDERBOOB BODYSUIT", "A bodysuit from clasps and straps.", "item_bsuit_2", type="bsuit", thong=True, braless=True, value=80, exposed_ass=True, exposed_nips=True)
    $ item_bsuit_3 = Item("FRILLY BODYSUIT", "A sexy bodysuit with frills.", "item_bsuit_3", type="bsuit", value=80, exposed_ass="pri", exposed_nips="pri", exposed_vag="pri")
    $ item_bsuit_4 = Item("THONG LEOTARD", "A leotard and body shaper.", "item_bsuit_4", type="bsuit", value=80, thong=True, exposed_ass=True, exposed_nips="pri", exposed_vag="pri")
    $ item_bsuit_5 = Item("OPEN BODYSUIT", "A bodysuit that leaves all the parts you usually want to cover up, open.", "item_bsuit_5", type="bsuit", value=80, pantsless=True, braless=True, exposed_ass=True, exposed_nips=True, exposed_vag=True)
    $ item_bsuit_6 = Item("MESHED BODYSUIT", "An elegant bodysuit that shapes while looking sexy.", "item_bsuit_6", type="bsuit", value=80, thong=True, exposed_ass=True, exposed_nips="pri")

    $ item_socks_1 = Item("TIGHTS", "A simple pair of tights reaching to the waist.", "item_socks_1", type="socks", value=50)
    $ item_socks_2 = Item("GLOSS TIGHTS", "A pair of glossy, waist high tights.", "item_socks_2", type="socks", value=50)
    $ item_socks_3 = Item("GLOSS THIGH HIGHS", "A pair of glossy thigh high stockings.", "item_socks_3", type="socks", value=30)
    $ item_socks_4 = Item("PLAIN THIGH HIGHS", "A pair of plain thigh high socks.", "item_socks_4", type="socks", value=30)
    $ item_socks_5 = Item("THIN STRIPE THIGH HIGHS", "A pair of stripped thigh high socks.", "item_socks_5", type="socks", value=30)
    $ item_socks_6 = Item("BOLD STRIPE THIGH HIGHS", "A pair of stripped thigh high socks.", "item_socks_6", type="socks", value=30)
    $ item_socks_7 = Item("BARGIRL SOCKS", "Uniform issued socks with a stop frill.", "item_socks_7", type="socks", value=40, locked_always=True)
    $ item_socks_8 = Item("GARTER BELT AND STOCKINGS", "A classic garter belt holding up stockings.", "item_socks_8", type="socks", value=150)
    $ item_socks_9 = Item("BUM HIGH SOCKS", "Socks that go right up to the persons crotch. Can be mistaken for leggings.", "item_socks_9", type="socks", value=100)
    $ item_socks_10 = Item("POINTED THIGH HIGHS", "Set of thigh high socks/stockings with a pointed front.", "item_socks_10", type="socks", value=100)
    $ item_socks_11 = Item("DIAMOND THIGH HIGHS", "Set of thigh high socks/stockings with a diamond pattern front.", "item_socks_11", type="socks", value=100)
    $ item_socks_12 = Item("HIGH HIP SOCKS", "A set of high hip socks, often called reverse bunny.", "item_socks_12", type="socks", value=150)
    $ item_socks_13 = Item("HIGH WAIST LEGGINGS", "A pair of simple leggings for the cold weather.", "item_socks_13", type="socks", value=150)
    $ item_socks_14 = Item("MAID KNEE HIGH SOCKS", "A pair of knee high socks with a frill trim.", "item_socks_14", type="socks", value=50, locked_always=True)
    $ item_socks_15 = Item("POLKA DOT THIGH HIGHS", "A pair of polka dot thigh high socks.", "item_socks_15", type="socks", value=30)
    $ item_socks_16 = Item("POLKA AND STRIPED KNEE HIGHS", "A mixed pair of polka dot and striped thigh high socks.", "item_socks_16", type="socks", value=30, locked_always=True)
    $ item_socks_17 = Item("KNEE PADS", "Perfect for when you spend a lot of time on your knees.", "item_socks_17", type="socks", value=50, locked=True)
    $ item_socks_18 = Item("CAT SOCKS", "A cute pair of socks with cat ears and cat face. Meow!", "item_socks_18", type="socks", value=50)
    $ item_socks_19 = Item("LATEX BOOTS", "A pair of thigh high latex boots. Shiny!", "item_socks_19", type="socks", value=100)
    $ item_socks_20 = Item("HUCOW SOCKS", "A pair of thigh high socks with a cow print.", "item_socks_20", type="socks", value=100, locked_always=True)
    $ item_socks_21 = Item("MISS SANTA SOCKS", "A pair of thigh high socks with a fluffy top.", "item_socks_21", type="socks", value=100, locked_always=True)


    $ item_outfit_1 = Item("HOSPITAL GOWN", "A typical hospital gown. This one does not expose the arse of it's wearer", "item_outfit_1", type="outfit", outfit=[], skirt=True, locked_always=True)
    $ item_outfit_2 = Item("SCHOOL SWIMSUIT", "A standard issue school swimsuit. While still revealing, it is quite modest as far as swimsuits go.", "item_outfit_2", type="outfit", outfit=["swim"], ass=True, pokenips=True, value=70)
    $ item_outfit_3 = Item("SLEEVELESS SUMMER DRESS", "A simple sleeveless summer dress. Modest top area and ends at the knee.", "item_outfit_3", type="outfit", outfit=["daily", "party"], skirt=True, value=70)
    $ item_outfit_4 = Item("LOW CUT BODYCON DRESS", "A low cut body conscious dress. Very tight and reveals your figure as well as a deep neckline.", "item_outfit_4", type="outfit", outfit=["daily", "party"], skirt=True, clevage=True, pokenips=True, ass=True, slutty=True, value=150, exposed_nips="pri", exposed_ass="pri", exposed_vag="pri")
    $ item_outfit_5 = Item("COMPETITION SWIMSUIT", "A swimsuit typically worn by more competitive swimmers.", "item_outfit_5", type="outfit", outfit=["swim"], ass=True, pokenips=True, value=130)
    $ item_outfit_6 = Item("BARGIRL DRESS", "A dress worn while working at the cock and goose. Cleavage on display and a very short skirt. Perfect for getting the punters' attention.", "item_outfit_6", type="outfit", outfit=["daily", "party"], skirt=True, slutty=True, pokenips=True, clevage=True, locked_always=True)
    $ item_outfit_7 = Item("SHOULDER WRAP DRESS", "An elegant evening dress with a shoulder wrap design. Perfect mix between looking beautiful and modest.", "item_outfit_7", type="outfit", outfit=["daily", "party"], skirt=True, value=170)
    $ item_outfit_8 = Item("BACKLESS MINIDRESS", "A backless strappy dress with a high skirt line. Perfect for getting any mans attention.", "item_outfit_8", type="outfit", outfit=["daily", "party"],ass=True, clevage=True, slutty=True, pokenips=True, skirt=True, value=240, exposed_nips="pri", exposed_ass="pri", exposed_vag="pri")
    $ item_outfit_9 = Item("BODY RAGS", "A dress cobbled together with scraps of cloth.", "item_outfit_9", type="outfit", outfit=["daily", "party"], ass=True, skirt=True, slutty=True, pokenips=True, clevage=True, value=5, exposed_nips=True, exposed_ass=True, exposed_vag="pri", locked_always=True)
    $ item_outfit_10 = Item("MATERNITY BODYCON DRESS", "A bodycon dress popular with pregnant women thanks to it's stretchable fabric.", "item_outfit_10", type="outfit", outfit=["daily", "party"], skirt=True, ass=True, pokenips=True, value=160, exposed_nips="pri", exposed_ass="sec", exposed_vag="sec")
    $ item_outfit_11 = Item("STRAPLESS BODYCON MINIDRESS", "A strapless minidress that is often seen being worn by women of negotiable affection.", "item_outfit_11", type="outfit", outfit=["daily", "party"], ass=True, skirt=True, slutty=True, pokenips=True, clevage=True, value=120, exposed_nips="pri", exposed_ass="pri", exposed_vag="pri")
    $ item_outfit_12 = Item("HALTER DRESS", "A deep v halter dress with a high cut side seam.", "item_outfit_12", type="outfit", outfit=["daily", "party"], ass=True, skirt=True, slutty=True, pokenips=True, clevage=True, value=260, exposed_nips="pri", exposed_ass="pri", exposed_vag="pri")
    $ item_outfit_13 = Item("STRAPPY LOINCLOTH DRESS", "A dress with a modest upper body but very revealing lower. If you forego underwear then you will almost certainly expose yourself to anyone who sees you", "item_outfit_13", type="outfit", outfit=["daily", "party"], ass=True, skirt=True, slutty=True, pokenips=True, clevage=True, value=260)
    $ item_outfit_14 = Item("PATCH DRESS", "A dress with a sheer under layer and patches placed to hide your more delicate bits.", "item_outfit_14", type="outfit", outfit=["daily", "party"], ass=True, skirt=True, slutty=True, pokenips=True, clevage=True, value=260)
    $ item_outfit_15 = Item("50's STYLE DRESS", "A modest dress associated with 1950's American housewives.", "item_outfit_15", type="outfit", outfit=["daily", "party"], skirt=True, value=260)
    $ item_outfit_16 = Item("CASINO DRESS", "A short and low cut dress worn by the servers at the casino", "item_outfit_16", type="outfit", outfit=["daily", "party"], skirt=True, clevage=True, slutty=True, pokenips=True, value=260)
    $ item_outfit_17 = Item("CORSET DRESS", "A short dress with a corset upper body that enhances form and shows off more than just a litle.", "item_outfit_17", type="outfit", outfit=["daily", "party"], skirt=True, clevage=True, slutty=True, pokenips=True, value=260)
    $ item_outfit_18 = Item("BUNNY LEOTARD", "A skimpy leotard wit a bunny tail.", "item_outfit_18", type="outfit", outfit=["daily", "party"], ass=True, clevage=True, thong=True, slutty=True, pokenips=True, value=300, locked_always=True)
    $ item_outfit_19 = Item("SHORTS DUNGAREES", "A pair of dungaree overalls in shorts design.", "item_outfit_19", type="outfit", outfit=["daily"], ass=True, value=300)
    $ item_outfit_20 = Item("MAID DRESS", "A classic maid dress.", "item_outfit_20", type="outfit", outfit=["daily", "party", "home"], ass=True, clevage=True, thong=True, slutty=True, skirt=True, pokenips=True, value=150, locked_always=True)
    $ item_outfit_21 = Item("PUFF SLEEVED DRESS", "A dress with puffed sleeves and a low cut front.", "item_outfit_21", type="outfit", outfit=["daily", "party"], clevage=True, slutty=True, skirt=True, pokenips=True, value=350)
    $ item_outfit_22 = Item("T-SHIRT DRESS", "A dress in the style of a very long t-shirt.", "item_outfit_22", type="outfit", outfit=["daily", "party", "sport", "home"], skirt=True, pokenips=True, value=70)
    $ item_outfit_23 = Item("FRILLY DRESS", "An elegant, puffy skirt dress that is perfect for formal occasions.", "item_outfit_23", type="outfit", outfit=["daily", "party"], skirt=True, pokenips=True, value=500)
    $ item_outfit_24 = Item("BUSTIER LOIN DRESS", "A bustier dress with a loin dress front and back.", "item_outfit_24", type="outfit", outfit=["daily", "party"], skirt=True, pokenips=True, slutty=True, clevage=True, ass=True, value=350, exposed_nips="pri", exposed_ass="pri", exposed_vag="pri")
    $ item_outfit_25 = Item("GOTHIC DRESS", "A long, puffy and frilly dress in a gothic style.", "item_outfit_25", type="outfit", outfit=["daily", "party"], skirt=True, pokenips=True, clevage=True, value=800)
    $ item_outfit_26 = Item("HIGH LEG DRESS", "A low cut dress with a very high leg line.", "item_outfit_26", type="outfit", outfit=["daily", "party"], skirt=True, pokenips=True, clevage=True, ass=True, slutty=True, value=400, exposed_nips="pri", exposed_ass="pri", exposed_vag="pri")
    $ item_outfit_27 = Item("CHEONGSAM", "A traditional chinese dress.", "item_outfit_27", type="outfit", outfit=["daily", "party"], skirt=True, pokenips=True, value=600)
    $ item_outfit_28 = Item("ORIENTAL DRESS", "A sexualised version of a traditional oriental dress.", "item_outfit_28", type="outfit", outfit=["daily", "party"], skirt=True, pokenips=True, slutty=True, clevage=True, ass=True, value=250, exposed_nips="pri", exposed_ass="pri", exposed_vag="pri")
    $ item_outfit_29 = Item("SHOULDER PUFF DRESS", "A modest dress with puffy shoulders.", "item_outfit_29", type="outfit", outfit=["daily", "party"], skirt=True, value=120)
    $ item_outfit_30 = Item("DEEP HALTER DRESS", "A halter dress with a deep v reaching the belly button.", "item_outfit_30", type="outfit", outfit=["daily", "party"], skirt=True, pokenips=True, clevage=True, slutty=True, value=300, exposed_nips="pri", exposed_ass="pri", exposed_vag="pri")
    $ item_outfit_31 = Item("WAISTBAND DRESS", "A dress with a large waistband.", "item_outfit_31", type="outfit", outfit=["daily", "party"], skirt=True, clevage=True, value=300)
    $ item_outfit_32 = Item("LATEX CATSUIT", "A full body latex catsuit. Shiny.", "item_outfit_32", type="outfit", outfit=["daily", "party"], ass=True, slutty=True, pokenips=True, value=300)
    $ item_outfit_33 = Item("LATEX DRESS", "A latex dress. Shiny.", "item_outfit_33", type="outfit", outfit=["daily", "party"], ass=True, slutty=True, skirt=True, pokenips=True, value=300)
    $ item_outfit_34 = Item("LATEX OPEN DRESS", "A latex dress with an open boob window. Shiny.", "item_outfit_34", type="outfit", outfit=["daily", "party"], ass=True, slutty=True, skirt=True, pokenips=True, value=300)
    $ item_outfit_35 = Item("T-SHIRT DRESS", "A dress with a t-shirt design. Has straps and a collar for detail.", "item_outfit_35", type="outfit", outfit=["daily", "party"], ass=True, skirt=True, pokenips=True, value=250, locked_always=True)
    $ item_outfit_36 = Item("HIGH LEG GOWN", "A gown with a high let slit. Low cut with sleeves", "item_outfit_36", type="outfit", outfit=["daily", "party"], ass=True, skirt=True, slutty=True, pokenips=True, value=400)
    $ item_outfit_37 = Item("CRUMPLE DRESS", "A dress with a crumple effect", "item_outfit_37", type="outfit", outfit=["daily", "party"], ass=True, skirt=True, slutty=True, pokenips=True, value=400)
    $ item_outfit_38 = Item("ROMPER", "A one piece romper", "item_outfit_38", type="outfit", outfit=["daily", "party", "home"], ass=True, pokenips=True, value=400)
    $ item_outfit_39 = Item("RUFFLED BABYDOLL", "A sheer pair of pyjamas with ruffles barely leaving something to the imagination.", "item_outfit_39", type="outfit", outfit=["daily", "party", "home"], ass=True, skirt=True, slutty=True, clevage=True, value=200, exposed_ass=True, exposed_vag=True)
    $ item_outfit_40 = Item("OPEN CHEST ROMPER SHORTS", "A one piece romper with short legs and an open square chest.", "item_outfit_40", type="outfit", outfit=["daily", "party", "home"], ass=True, clevage=True, value=200)
    $ item_outfit_41 = Item("SHOULDER ROMPER", "A one piece romper with open shoulders.", "item_outfit_41", type="outfit", outfit=["daily", "party", "home"], ass=True, clevage=True, value=200)
    $ item_outfit_42 = Item("SHOULDER ROMPER", "A one piece romper with open shoulders.", "item_outfit_42", type="outfit", outfit=["daily", "party", "home"], ass=True, clevage=True, value=200)



    $ item_top_1 = Item("TRIANGLE BIKINI", "A small bikini top with thin straps holding triangle pads to hide your nipples. Doesn't hide much else.", "item_top_1", type="top", outfit=["swim"], clevage=True, belly=True, pokenips=True, slutty=True, value=70, exposed_nips="pri")
    $ item_top_2 = Item("BOW BIKINI", "A strapless bikini top that ties at the front with an elegant knot.", "item_top_2", type="top", outfit=["swim"], clevage=True, belly=True, pokenips=True, value=120)
    $ item_top_3 = Item("MICRO BIKINI", "A tiny bikini top with some pads that barely hide anything that is held together by string like straps.", "item_top_3", type="top", outfit=["swim"], clevage=True, belly=True , slutty=True, pokenips=True, value=50, exposed_nips="pri")
    $ item_top_4 = Item("LOOSE TEE", "A loose fitting tented t-shirt.", "item_top_4", type="top", belly=True, pokenips=True, value=130, exposed_nips="pri")
    $ item_top_5 = Item("TANK TOP", "A tight tank top help up by straps and cuts off above the stomach.", "item_top_5", type="top", outfit=["daily", "party", "sport", "home"], clevage=True, belly=True, pokenips=True, value=130, exposed_nips="pri")
    $ item_top_6 = Item("ELASTIC VEST", "A stretch fit vest usually worn as an under garment.", "item_top_6", type="top", outfit=["daily", "party", "sport", "home"], belly=True, pokenips=True, value=200, exposed_nips="pri")
    $ item_top_7 = Item("ELASTIC T-SHIRT", "A stretch fit t-shirt usually worn as an under garment.", "item_top_7", type="top", outfit=["daily", "party", "sport", "home"], belly=True, pokenips=True, value=200, exposed_nips="pri")
    $ item_top_8 = Item("VOLLEYBALL TOP", "A volleyball top. Sleeveless for excellent mobility with ventilation at the sides, back and shoulders.", "item_top_8", type="top", outfit=["daily", "sport", "home"], pokenips=True, value=40)
    $ item_top_9 = Item("CROPPED T SHIRT", "A simple cropped T-shirt that shows off your belly.", "item_top_9", type="top", belly=True, pokenips=True, value=80)
    $ item_top_10 = Item("STRAPPY BRA TOP", "A fitted bra top with fashionable straps and a frilly hem.", "item_top_10", type="top", outfit=["daily", "party"], belly=True, pokenips=True, clevage=True, value=130)
    $ item_top_11 = Item("LOOSE CROPTOP", "A loose crop top that is only held up by the straps.", "item_top_11", type="top", outfit=["daily", "party"], clevage=True, belly=True, value=90, locked=True)
    $ item_top_12 = Item("PLAIN SHIRT", "A standard collared shirt for girls with simple short sleeves.", "item_top_12", type="top",outfit=["school", "daily", "party"], pokenips=True, value=50)
    $ item_top_13 = Item("HALTER TOP", "A deep v halter top held around the waist.", "item_top_13", type="top", outfit=["daily", "party"], clevage=True, belly=True, pokenips=True, slutty=True, value=170, exposed_nips="pri")
    $ item_top_14 = Item("KNOTTED SHIRT", "A deep v shirt designed to be tied at the front.", "item_top_14", type="top", outfit=["school", "daily", "party"], clevage=True, belly=True, pokenips=True, slutty=True, value=120, exposed_nips="pri")
    $ item_top_15 = Item("SHOULDERLESS T-SHIRT", "A form fitting shoulder less t-shirt for girls.", "item_top_15", type="top", outfit=["daily", "party"], clevage=True, belly=True, pokenips=True, value=150, exposed_nips="pri")
    $ item_top_16 = Item("BARDOT CROP TOP", "An off the shoulder crop top with a lettuce trim pattern.", "item_top_16", type="top", outfit=["daily", "party"], clevage=True, belly=True, pokenips=True, value=170)
    $ item_top_17 = Item("SLEEVELESS TURTLENECK", "A simple sleeveless top with a high neckline.", "item_top_17", type="top", outfit=["daily", "party"], belly=True, pokenips=True, value=200)
    $ item_top_18 = Item("LOOSE VEST", "A small, loose hanging vest.", "item_top_18", type="top", outfit=["daily", "sport", "party", "home"], belly=True, pokenips=True, clevage=True, value=200, exposed_nips="pri")
    $ item_top_19 = Item("UNDERBOOB CROP TOP", "A tiny top that hides almost nothing. Should be worn with a bra underneath.", "item_top_19", type="top", outfit=["daily", "sport", "party", "home"], belly=True, pokenips=True, clevage=True, slutty=True, value=150, locked=True, exposed_nips="pri")
    $ item_top_20 = Item("KNOTTED TEE", "A loose t-shirt designed for a mix of fashion and flexibility. Good to wear day to day or while working out.", "item_top_20", type="top", outfit=["daily", "sport", "party", "home"], belly=True, pokenips=True, value=150, locked=True)
    $ item_top_21 = Item("CHEST RAGS", "Some torn rags that try to give me some modesty.", "item_top_21", type="top", outfit=["daily", "party"], belly=True, pokenips=True, clevage=True, slutty=True, value=5, exposed_nips="pri", locked_always=True)
    $ item_top_22 = Item("SHEER DROP TOP", "A Thin top held loosely by thin shoulder straps and left to hang on the body.", "item_top_22", type="top", outfit=["daily", "party"], belly=True, pokenips=True, clevage=True, slutty=True, value=250, exposed_nips="pri")
    $ item_top_23 = Item("LOOSE SPORTS TOP", "A thin and loose sports top allowing for excellent mobility and breathability.", "item_top_23", type="top", outfit=["daily", "sport", "home"], belly=True, pokenips=True, clevage=True, value=250, exposed_nips="pri")
    $ item_top_24 = Item("FORM FITTING SWEATER", "A thin and form fitting sweater. Perfect for chilly nights or working out in the winter", "item_top_24", type="top", outfit=["daily", "sport", "home"], pokenips=True, value=250)
    $ item_top_25 = Item("LONG VEST", "A thin and form fitting sweater. Perfect for chilly nights or working out in the winter", "item_top_25", type="top", outfit=["daily", "sport", "home"], pokenips=True, value=250, exposed_nips="pri")
    $ item_top_26 = Item("SLEEVELESS SHIRT", "A collared sleeveless shirt with a pointed lower trim.", "item_top_26", type="top", outfit=["daily", "school", "party"], pokenips=True, value=250, exposed_nips="pri")
    $ item_top_27 = Item("HEART PATCH TOP", "A top with heart patches.", "item_top_27", type="top", outfit=["daily", "sport", "home"], pokenips=True, value=50)
    $ item_top_28 = Item("HARLEQUIN TOP", "A top in a harlequin style.", "item_top_28", type="top", outfit=["daily", "sport", "home"], pokenips=True, value=50, locked_always=True)
    $ item_top_29 = Item("RAGGED T-SHIRT", "A t-shirt that is mostly rags now.", "item_top_29", type="top", pokenips=True, slutty=True, value=5, exposed_nips="pri", locked_always=True)
    $ item_top_30 = Item("BOOB WINDOW SWEATER", "A loose shoulder hung top with a boob window.", "item_top_30", type="top", outfit=["daily", "party"], pokenips=True, clevage=True, value=130)

    $ item_top_32 = Item("MESH TOP", "A form fitting top with a mesh window.", "item_top_32", type="top", outfit=["daily", "sport", "party", "home"], clevage=True, belly=True, slutty=True, pokenips=True, value=200)
    $ item_top_33 = Item("STRAPPY TOP", "A short top with cross style shoulder straps.", "item_top_33", type="top", outfit=["daily", "sport", "party", "home"], clevage=True, belly=True, slutty=True, pokenips=True, value=200, exposed_nips="pri")
    $ item_top_34 = Item("BUSTIER TOP", "A strapless bustier top.", "item_top_34", type="top", outfit=["daily", "party", "home"], clevage=True, belly=True, slutty=True, pokenips=True, value=200, exposed_nips="pri")
    $ item_top_35 = Item("BOOB WINDOW TOP", "A tight top with a large boob window.", "item_top_35", type="top", outfit=["school", "daily", "party", "home"], clevage=True, belly=True, slutty=True, pokenips=True, value=200, exposed_nips="pri")
    $ item_top_36 = Item("BOOB TUBE", "A small and revealing boob tube.", "item_top_36", type="top", outfit=["school", "daily", "party", "home"], pokenips=True, clevage=True, belly=True, slutty=True, value=30, exposed_nips="pri")
    $ item_top_37 = Item("DEEP V T-SHIRT", "A t-shirt with a deep v neckline.", "item_top_37", type="top", outfit=["school", "daily", "party", "home"], pokenips=True, clevage=True, belly=True, slutty=True, value=80, exposed_nips="pri")
    $ item_top_38 = Item("SHOULDER TOP", "An off the shoulder top with long sleeves.", "item_top_38", type="top", outfit=["school", "daily", "party", "home"], pokenips=True, clevage=True, belly=True, slutty=True, value=80)
    $ item_top_39 = Item("LATEX TOP", "A long sleeve, latex crop top. Shiny.", "item_top_39", type="top", outfit=["daily", "party"], slutty=True, pokenips=True, value=100)
    $ item_top_40 = Item("T-SHIRT", "A simple t-shirt like the one Jaylee wears", "item_top_40", type="top", outfit=["daily", "sport", "home"], value=50, locked=True)
    $ item_top_41 = Item("DRAPE TOP", "A shoulder hanging drape top.", "item_top_41", type="top", outfit=["daily", "sport", "home", "party"], pokenips=True, clevage=True, belly=True, slutty=True, value=80, exposed_nips="pri")
    $ item_top_42 = Item("RUFFLED TOP", "A revealing ruffled chest covering.", "item_top_42", type="top", outfit=["daily", "sport", "home", "party"], clevage=True, belly=True, slutty=True, value=80, exposed_nips="pri")
    $ item_top_43 = Item("MISS SANTA TOP", "A fluffy santa bustier.", "item_top_43", type="top", outfit=["daily", "sport", "home", "party"], clevage=True, belly=True, value=80, locked_always=True)
    $ item_top_44 = Item("SLEEVELESS MUFFLER TOP", "A sleeveless top with a neck muffler.", "item_top_44", type="top", outfit=["daily", "sport", "home"], belly=True, pokenips=True, value=80)
    $ item_top_45 = Item("BAGGY SHIRT", "A simple, very loose, short sleeved dress shirt.", "item_top_45", type="top", outfit=["daily", "school", "party"], belly=True, pokenips=True, value=80)
    $ item_top_46 = Item("SHOULDERLESS T-SHIRT", "A typical t-shirt with the shoulders cut out for extra flexibility and ventilation.", "item_top_46", type="top", outfit=["daily", "sport", "home"], belly=True, pokenips=True, value=80)


    $ item_bottom_1 = Item("SIDE KNOT BIKINI BOTTOMS", "Simple pair of bikini bottoms that tie up at the sides.", "item_bottom_1", type="bottom", outfit=["swim"], ass=True, slutty=True, value=70, exposed_vag="pri")
    $ item_bottom_2 = Item("BOW BIKINI BOTTOMS", "A pair of bikini bottoms with a decorative side bow.", "item_bottom_2", type="bottom", outfit=["swim"], ass=True, value=120)
    $ item_bottom_3 = Item("MICRO BIKINI BOTTOMS", "A pair of micro bikini bottoms that barely cover the front and have a thong back.", "item_bottom_3", type="bottom", outfit=["swim"], ass=True, thong=True, slutty=True, value=50, exposed_vag="pri", exposed_ass=True)
    $ item_bottom_4 = Item("FORMAL TROUSERS", "A pair of typical formal trousers. They even have pockets.", "item_bottom_4", type="bottom", outfit=["school", "daily", "party"], ass=True, value=160)
    $ item_bottom_5 = Item("PLEATED SKIRT", "An above the knee pleated skirt.", "item_bottom_5", type="bottom", outfit=["school", "daily", "party"], skirt=True, value=120)
    $ item_bottom_6 = Item("WIDE PLEAT SKIRT ", "An above the knee skirt with wide box pleats.", "item_bottom_6", type="bottom", outfit=["school", "daily", "party"], skirt=True, value=120)
    $ item_bottom_7 = Item("FLARED SKIRT", "An above the knee skirt that flairs at the bottom.", "item_bottom_7", type="bottom", outfit=["school", "daily", "party"], skirt=True, value=120)
    $ item_bottom_8 = Item("VOLLEYBALL SHORTS", "Volleyball shorts. Good mobility with possible ventilation at the sides.", "item_bottom_8", type="bottom", outfit=["sport"], ass=True, value=30)
    $ item_bottom_9 = Item("YOGA PANTS", "Stretchy, great mobility and form fitting. Great for working out or just lounging around the house.", "item_bottom_9", type="bottom", outfit=["daily", "sport", "home"], ass=True, value=90)
    $ item_bottom_10 = Item("DENIM SHORTS", "A pair of low rise jean shorts. Fairly tight with a high leg line.", "item_bottom_10", type="bottom", outfit=["daily"], ass=True, locked=True)
    $ item_bottom_11 = Item("MICRO MINISKIRT", "A tiny miniskirt that leaves little to the imagination. Popular with girls of the night.", "item_bottom_11", type="bottom", outfit=["school", "daily", "party"], ass=True, skirt=True, slutty=True, value=40, exposed_vag="pri", exposed_ass="pri")
    $ item_bottom_12 = Item("SIDE STRAP TROUSERS", "A pair of trousers held up by side straps giving a look of sexiness while not having to worry about a skirt.", "item_bottom_12", type="bottom", outfit=["daily", "party"], ass=True, slutty=True, value=230)
    $ item_bottom_13 = Item("DANCE MINI SKIRT", "A micro mini skirt designed for maximum movement while dancing or doing other types of exercise.", "item_bottom_13", type="bottom", outfit=["daily", "school", "sport", "party", "home"], skirt=True, slutty=True, value=140, locked=True)
    $ item_bottom_14 = Item("RAGGY SKIRT", "Some rags wrapped around to fashion some kind of skirt.", "item_bottom_14", type="bottom", outfit=["daily", "party"], ass=True, skirt=True, slutty=True, value=5, exposed_ass=True, locked_always=True)
    $ item_bottom_15 = Item("PLEATED MINI SKIRT", "A pleated micro mini skirt that doesn't offer a lot of modesty.", "item_bottom_15", type="bottom", outfit=["daily", "school", "party"], skirt=True, slutty=True, value=180)
    $ item_bottom_16 = Item("SPORTY SHORTS", "A short pair of shorts that allow excellent mobility while working out.", "item_bottom_16", type="bottom", outfit=["daily", "sport", "home"], ass=True, slutty=True, value=180)
    $ item_bottom_17 = Item("FLARED SHORTS", "A heavily flared pair of shorts giving maximum movement and freedom. Often mistaken for a skirt.", "item_bottom_17", type="bottom", outfit=["daily", "sport", "home"], ass=True, value=180)
    $ item_bottom_18 = Item("TORN JEAN SHORTS", "Stylishly torn jean shorts.", "item_bottom_18", type="bottom", outfit=["daily", "party"], ass=True, value=180)
    $ item_bottom_19 = Item("FRILLY TIGHT SKIRT", "A form fitting but smart looking skirt with lower frills.", "item_bottom_19", type="bottom", outfit=["daily", "party", "school"], ass=True, skirt=True, value=180, exposed_vag="pri", exposed_ass="pri")
    $ item_bottom_20 = Item("HIGH WAIST PENCIL SKIRT", "A high wasted low cut skirt for professional wear.", "item_bottom_20", type="bottom", outfit=["daily", "party", "school"], ass=True, skirt=True, slutty=True, value=250)
    $ item_bottom_21 = Item("HEART PATCH SHORTS", "A pair of comfortable shorts with heart patches on them.", "item_bottom_21", type="bottom", outfit=["daily", "sport", "home"], ass=True, value=50)
    $ item_bottom_22 = Item("HARLEQUIN SHORTS", "A pair of shorts in a harlequin style.", "item_bottom_22", type="bottom", outfit=["daily", "sport", "home"], ass=True, value=50, locked_always=True)
    $ item_bottom_23 = Item("LOW RISE JEANS", "A pair of form fitting low rise jeans.", "item_bottom_23", type="bottom", outfit=["daily", "party", "school"], ass=True, value=200)
    $ item_bottom_24 = Item("RAGGED JEANS", "What was once a pair of form fitting jeans is now mostly holes.", "item_bottom_24", type="bottom", outfit=["daily", "party", "school"], ass=True, slutty=True, value=10)
    $ item_bottom_25 = Item("RIPPED SKIRT", "Some rags fashioned into a makeshift skirt.", "item_bottom_25", type="bottom", ass=True, slutty=True, skirt=True, value=5, exposed_ass=True)
    $ item_bottom_26 = Item("SWEAT PANTS", "A low rise pair of workout sweat pants.", "item_bottom_26", type="bottom", outfit=["daily", "sport", "home"], ass=True, value=60)
    $ item_bottom_27 = Item("WORKOUT SHORTS", "A simple pair of sweat shorts for working out in.", "item_bottom_27", type="bottom", outfit=["daily", "sport", "home"], ass=True, value=60)
    $ item_bottom_28 = Item("MICRO MINI SKIRT", "A wrap around micro mini skirt.", "item_bottom_28", type="bottom", outfit=["school", "daily", "party", "home"], ass=True, skirt=True, slutty=True, value=60, exposed_vag="pri", exposed_ass=True)
    $ item_bottom_29 = Item("HIGH BAND SWEATPANTS", "A high waisted pair of baggy sweatpants.", "item_bottom_29", type="bottom", outfit=["daily", "sport", "home"], value=150)
    $ item_bottom_30 = Item("HIGH WAIST MINISKIRT", "A high waist high hemline skirt.", "item_bottom_30", type="bottom", outfit=["school" ,"daily", "party"], ass=True, skirt=True, slutty=True, value=130, exposed_vag="pri", exposed_ass="pri")
    $ item_bottom_31 = Item("LATEX TROUSERS", "A pair of latex trousers. Shiny.", "item_bottom_31", type="bottom", outfit=["daily", "party"], ass=True, slutty=True, value=130)
    $ item_bottom_32 = Item("JEAN SHORTS", "A pair of jean shorts similar to the ones Jaylee wears.", "item_bottom_32", type="bottom", outfit=["daily"], ass=True, value=130, locked=True)
    $ item_bottom_33 = Item("WRAP SKIRT", "A knotted wrap skirt. Should be tied at the side.", "item_bottom_33", type="bottom", outfit=["daily", "party", "sport", "home"], ass=True, slutty=True, skirt=True, value=130, exposed_vag=True, exposed_ass="pri")
    $ item_bottom_34 = Item("RUFFLED SKIRT", "A ruffled skirt that barely covers anything.", "item_bottom_34", type="bottom", outfit=["daily", "party", "sport", "home"], ass=True, slutty=True, skirt=True, value=130, exposed_vag=True, exposed_ass=True)
    $ item_bottom_35 = Item("MISS SANTA SKIRT", "A skirt with a fluffy trim.", "item_bottom_35", type="bottom", outfit=["daily", "party", "sport", "home"], skirt=True, value=130, locked_always=True)
    $ item_bottom_36 = Item("WORKOUT BLOOMERS", "Stretchy and form fitting shorts for working out in.", "item_bottom_36", type="bottom", outfit=["daily", "sport", "home"], ass=True, value=130)
    $ item_bottom_37 = Item("DRESS TROUSERS", "A pair of smart looking dress trousers.", "item_bottom_37", type="bottom", outfit=["daily", "party", "school"], ass=True, value=130)
    $ item_bottom_38 = Item("YOGA SHORTS", "Very form fitting but also stretchy pair of workout shorts.", "item_bottom_38", type="bottom", outfit=["daily", "sport", "home"], ass=True, value=130)
    $ item_bottom_39 = Item("MINI DAISY DUKES", "A pair of low rise jeans, cut off at the bottom to form a pair of hot pants.", "item_bottom_39", type="bottom", outfit=["daily", "sport", "home"], ass=True, slutty=True, value=80)

    $ item_gloves_1 = Item("FINGERLESS GLOVES", "A pair of fingerless gloves.", "item_gloves_1", type="gloves", value=40, locked=True)
    $ item_gloves_2 = Item("ARM WARMERS", "A striped pair of arm warmers.", "item_gloves_2", type="gloves", value=40)
    $ item_gloves_3 = Item("CASINO GLOVES", "A set of gloves/cuffs worn at the casino.", "item_gloves_3", type="gloves", value=40, locked_always=True)
    $ item_gloves_4 = Item("RUBBER GLOVES", "A set of rubber gloves for cleaning.", "item_gloves_4", type="gloves", value=10, locked=True)
    $ item_gloves_5 = Item("ELBOW PADS", "A pair of elbow pads.", "item_gloves_5", type="gloves", value=50, locked=True)
    $ item_gloves_6 = Item("HUCOW GLOVES", "A pair of elbow length gloves with a cow pattern.", "item_gloves_6", type="gloves", value=50, locked_always=True)
    $ item_gloves_7 = Item("MISS SANTA GLOVES", "A pair of fluffy wrist warmers", "item_gloves_7", type="gloves", value=50, locked_always=True)


    $ item_coat_1 = Item("HOODED COAT", "A short sleeve body warmer coat with a hood.", "item_coat_1", type="coat", value=500)
    $ item_coat_2 = Item("CROP SWEATER", "A cropped sweater with long sleeves.", "item_coat_2", type="coat", value=500)
    $ item_coat_3 = Item("BODY VEST", "An open front, sleeveless body warmer.", "item_coat_3", type="coat", value=500)
    $ item_coat_4 = Item("LONG COAT", "A thigh length coat with a high collar for keeping warm.", "item_coat_4", type="coat", value=500)
    $ item_coat_5 = Item("CASINO SERVER COAT", "A coat worn in the casino.", "item_coat_5", type="coat", value=500, exposed_nips=True, locked=True)
    $ item_coat_6 = Item("WAISTCOAT", "An elegant waistcoat perfect for formal occasions.", "item_coat_6", type="coat", value=500)
    $ item_coat_7 = Item("HEAVY SWEATER", "A very heavy sweater, useful as a coat in winter.", "item_coat_7", type="coat", value=500, covers_bottom=True)
    $ item_coat_8 = Item("BODY WARMER HOODIE", "A hoodie with no sleeves. Perfect for when it gets cold during summer nights.", "item_coat_8", type="coat", value=500)
    $ item_coat_9 = Item("ZIP HOODIE", "A front zip hoodie", "item_coat_9", type="coat", value=500)
    $ item_coat_10 = Item("CROPPED HOODIE", "A fairly simple hoodie that has been cropped, leaving the belly and underboob exposed.", "item_coat_10", type="coat", clevage=True, belly=True, value=500, locked=True)
    $ item_coat_11 = Item("BOYFRIEND T-SHIRT", "An over sized t-shirt usually stolen from a man. Does not come with boyfriend smell.", "item_coat_11", type="coat", value=300, covers_bottom=True)
    $ item_coat_12 = Item("BEAR ONESIE", "A big fluffy onesie that looks like a bear.", "item_coat_12", type="coat", value=500, covers_bottom=True)



    $ item_glasses_1 = Item("FAUX GLASSES", "Glasses designed to look like prescription glasses.", "item_glasses_1", type="glasses", value=350)
    $ item_glasses_2 = Item("AVIATORS", "Aviator sunglasses.", "item_glasses_2", type="glasses", value=350)
    $ item_glasses_3 = Item("HORN RIMMED SUNGLASSES", "A stylish pair of horn rimmed sunglasses.", "item_glasses_3", type="glasses", value=350)
    $ item_glasses_4 = Item("NERD GLASSES", "A pair of glasses as thick as the bottom of a glass bottle.", "item_glasses_4", type="glasses", value=350)
    $ item_glasses_5 = Item("READING GLASSES", "A small pair of round reading glasses.", "item_glasses_5", type="glasses", value=350)
    $ item_glasses_6 = Item("CASINO MASK", "A mask used to hide my identity while still allowing people to see most of my face.", "item_glasses_6", type="glasses", value=350)


    $ item_choker_1 = Item("CLASP COLLAR", "A collar with a metal front clasp.", "item_choker_1", type="choker", value=70)
    $ item_choker_2 = Item("THICK COLLAR", "A thick and restrictive collar.", "item_choker_2", type="choker", value=70)
    $ item_choker_3 = Item("CAT BELL COLLAR", "A simple collar with a cat's bell at the front.", "item_choker_3", type="choker", value=150)
    $ item_choker_4 = Item("BOW TIE COLLAR", "A shirt collar with a bow tie.", "item_choker_4", type="choker", value=150)
    $ item_choker_5 = Item("HUCOW COLLAR", "A bell collar like that of a cow.", "item_choker_5", type="choker", value=150, locked=True)
    $ item_choker_6 = Item("BITCH COLLAR", "A collar that indicates I am playing the wolf gauntlet. I will find myself in dangerous (but fun) situations wearing this.", "item_choker_6", type="choker", value=20, locked=True)


    $ item_nipring_1 = Item("NIPPLE RING", "A pair of nipple rings.", "item_nipring_1", type="nipring", value=350)



    $ item_navelring_1 = Item("NAVEL RING", "A navel ring.", "item_navelring_1", type="navelring", value=350)








    return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
