label school_newfriend_description:
    "NEW EVENT CHAIN -- New friend."
    "One the early days of school, possibly the second day or so. You will be approached by another person from the school who introduces themselves."
    "They will recognise you are new and offer to show you around the place. This will serve as a bit of a tutorial event to get you familiar with the general environment."
    "From here, you will get random events trigger where you bump into him and have a chat. He is always pleasant and friendly to you."
    "The idea is, it will seems like he is one of the very early game romance type options you see in many other games. This will lul you into a false sense of security."
    "At some point after school he will approach you and tell you he has managed to sneak some beers and if you want to join him."
    "You can freely reject him at this point and he will go away. He will approach once or twice more on other days and try the same. if you keep rejecting then this quest will quietly end."
    "He will no longer approach you but you can hear the odd rumour that makes it sound like he managed to trap other girls."
    "If you accept he will lead you to the boys changing rooms where he has them in a locker. You will either drink there or hang out in the bushes and drink them. not sure where yet."
    "You will hang out and drink and he will ply you with booze. At some point he will try it on with you and if you go along with it you will give him a blowjob."
    "During the blowjob his attitude will change slightly. It will at first just seem like sex talk. Calling you naughty names and the like. But once the blowjob is over he will continue talking to you like this."
    "You will end your date and go about your day"
    "Randomly around school he will approach you and offer to take you to the toilets/changing rooms for some fun. You can agree or refuse."
    "If you agree you will just go along with it."
    "If you refuse more than once though, he will reveal to you he has taken pics of you and if you don't want them spread around, you had better do as he tells you."
    "Depending on what you have done with him up to this point, he will comment about each act."
    "Since this is early game, there is a good chance that without the booze, you will not have the confidence to agree to his sex offers so this chain may trigger quite early."
    "You will be forced to do things with him to keep the pics a secret."

    "If you are being blackmailed and gain enough confidence to tell him to go away, he will threaten to spread the pics of you. I you still tell him to go away he will do so."
    "Later on you find out he did in fact spread the pics of you. Random guys at school mock you or ask to fuck you like he did. Special comments if he took your virginity or got you pregnant."
    "Eventually you will be approached by a couple of girls. He is also blackmailing them and making them do things. They believe there are other girls as well judging by how all the girls hate him."
    "So while the pics of you have spread, you are not the social outcast you may have feared you would become."
    "In the end, him spreading the pics gave other girls the confidence to tell him to piss off and he winds up getting a horrible reputation at school for being scum."
    "No girl will approach him, and if he approaches a girl, others quickly warn them and shoo him away."
    "Other guys no longer want to associate with him simply because if they do, the girls in the school will ignore them. So any friends he did have quickly abandon him."
    "He himself ends up a social outcast."
    "Your pics are still out there of course and you are still mocked now and then, but not much you can do at this point."
    jump travel
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
